name: Deploy

on:
  push:
    tags:
      - \d+\.\d+\.\d+

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update CHANGELOG
        id: update_changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          restrictToTypes: feat,fix,refactor,perf

      - name: Get latest tag
        id: get-latest-tag
        run: echo "LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      - name: Create package
        run: |
          cd ${{ github.workspace }}
          zip -r  ./mod_darkmode-${{ env.LATEST_TAG }}.zip \
                  ./* \
                  -x .github/ \

      - name: Extract Changelog Section
        id: extract_changelog
        run: |
          CHANGELOG_CONTENT=$(awk '/^## \['"${{ env.LATEST_TAG }}"'\]/,/^## \[/{print}' CHANGELOG.md)
          echo "::set-output name=content::$CHANGELOG_CONTENT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Dark Mode Switcher v${{ env.LATEST_TAG }}"
          body: ${{ steps.extract_changelog.outputs.content }}
          files: ./mod_darkmode-${{ env.LATEST_TAG }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: "docs: update CHANGELOG.md for ${{ github.ref_name }}"
          file_pattern: CHANGELOG.md
